// Abe in a few poses for the Basics form and results: the same head as Avatar.tsx on a small body.
// 48×48, transparent. Show at multiples of 48 (96, 144) so the pixels stay crisp.

import { toRects } from './pixels.ts'

type DrawnPose = 'wave' | 'point' | 'think' | 'clipboard' | 'thumbs' | 'cheer' | 'pointup' | 'ponder'
export type HoldPose = 'heart' | 'coin' | 'calendar' | 'hourglass' | 'umbrella'
export type PoseName = DrawnPose | HoldPose

// One letter per pixel, '.' is transparent. Letters map to the colors in pixels.ts.
const DRAWN: Record<DrawnPose, string[]> = {
  wave: [
    '................................................',
    '..................KKKKKKKKKKKK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KTttTTTTTTTK..................',
    '..................KTTTTTTTTTTK.....O............',
    '..............KAaaaaaAAAAAAAAAAAAKO.............',
    '...............KKKKKKKKKKKKKKKKKK...............',
    '...............HHhssssssssssssHHH....z.z.z...O..',
    '...............HHHHSSSSSSSSSSHHHH...zSzSzSz...O.',
    '................hHSBBBSSSSBBBSHH....zSSSSSz.....',
    '................zHSsssSSSSsssSHz...zSSSSSSz.....',
    '...............zSHSSwESSsSwESSHSz..zzsSSSSz..O..',
    '...............zSHSSEESSsSEESSHSz....zSSSz....O.',
    '................sDDCSSSSsSSSCDDs.....KccK.......',
    '................DdDDSMSzzSSSDDDD....KrccK.......',
    '................DdDDDSnmmnSDdDDD....KrccK.......',
    '................DDgDDDSSSSDDdDDD....KrJJK.......',
    '................DDDdDDDgDDDDDDDD....KrJJK.......',
    '.................KDdDDDgDdDgDdK....KrJJJK.......',
    '..................KDDdDDDdDDDK.....KrJJK........',
    '...................DDdDDgDDDD.....KrJJJK........',
    '.....................DDDDDD......KrJJJJK........',
    '.............KKK.KKYYYccccYYYKK.KrJJJJK.........',
    '............KrrrKJJYYYYyyYYYYJJKrJJJJK..........',
    '............KrJJKrJYYLecccLYYJJKrJJJK...........',
    '............KrJJKrJJJLLccLLJoJJKrJJK............',
    '............KrJJKrJJJJLLLLJJOJJKKKK.............',
    '............KrJJKrJJJJJJKJJJJJJK................',
    '............KrJJKrJJJJJaKJJJJJJK................',
    '............KccJKrJJJJJJKJJJJJJK................',
    '............KccJKrJJJJJJKJJJJJJK................',
    '............zSSzKrJJJJJaKJJJJJJK................',
    '...........zSSSSzKrJJJJJKJJJJJK.................',
    '............zSSz.KrJJJJJKJJJJJK.................',
    '.............zz..KrJJJJQQJJJJJK.................',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  point: [
    '................................................',
    '..................KKKKKKKKKKKK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KTttTTTTTTTK..................',
    '..................KTTTTTTTTTTK..................',
    '..............KAaaaaaAAAAAAAAAAAAK..............',
    '...............KKKKKKKKKKKKKKKKKK...............',
    '...............HHhssssssssssssHHH...............',
    '...............HHHHSSSSSSSSSSHHHH...............',
    '................hHSBBBSSSSBBBSHH................',
    '................zHSsssSSSSsssSHz................',
    '...............zSHSSwESSsSwESSHSz...............',
    '...............zSHSSEESSsSEESSHSz...............',
    '................sDDCSSSSsSSSCDDs................',
    '................DdDDSMSzzSSSDDDD................',
    '................DdDDDSnmmnSDdDDD................',
    '................DDgDDDSSSSDDdDDD................',
    '................DDDdDDDgDDDDDDDD................',
    '.................KDdDDDgDdDgDdK.................',
    '..................KDDdDDDdDDDK..................',
    '...................DDdDDgDDDD...................',
    '.....................DDDDDD.....................',
    '.............KKK.KKYYYccccYYYKK.KKKKKKKKKzz.....',
    '............KrrrKJJYYYYyyYYYYJJKrrrrrrrrrSSzzz..',
    '............KrJJKrJYYLecccLYYJJKrJJJJJJccSSSSSz.',
    '............KrJJKrJJJLLccLLJoJJKrJJJJJJccSSSz...',
    '............KrJJKrJJJJLLLLJJOJJKKKKKKrJJJSSz....',
    '............KrJJKrJJJJJJKJJJJJJK.....KKKKzz.....',
    '............KrJJKrJJJJJaKJJJJJJK................',
    '............KccJKrJJJJJJKJJJJJJK................',
    '............KccJKrJJJJJJKJJJJJJK................',
    '............zSSzKrJJJJJaKJJJJJJK................',
    '...........zSSSSzKrJJJJJKJJJJJK.................',
    '............zSSz.KrJJJJJKJJJJJK.................',
    '.............zz..KrJJJJQQJJJJJK.................',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  think: [
    '................................................',
    '..................KKKKKKKKKKKK..................',
    '..................KAaaAAAAAAAK............kk....',
    '..................KAaaAAAAAAAK...........kWWk...',
    '..................KAaAAAAAAAAK..........kWWWWk..',
    '..................KAaAAAAAAAAK.........kWWWWWWk.',
    '..................KAaAAAAAAAAK.........kWWWWWWk.',
    '..................KTttTTTTTTTK..........kWWWWk..',
    '..................KTTTTTTTTTTK...........kkkk...',
    '..............KAaaaaaAAAAAAAAAAAAK....kk........',
    '...............KKKKKKKKKKKKKKKKKK....kWWk.......',
    '...............HHhssssssssssssHHH....kWWk.......',
    '...............HHHHSSSSSSSSSSHHHH.....kk........',
    '................hHSBBBSSSSBBBSHH....k...........',
    '................zHSsssSSSSsssSHz...kWk..........',
    '...............zSHSSwESSsSwESSHSz...k...........',
    '...............zSHSSEESSsSEESSHSz...............',
    '................sDDCSSSSsSSSCDDs................',
    '................DdDDSMSzzSSSDDDD................',
    '................DdDDDSnmmnSDdDDD................',
    '................DDgDDDSSSSDDdDDD................',
    '................DDDdDDDgDDDDDDDD................',
    '.................KDzzzDgDdDgDdK.................',
    '..................zSSSzDDdDDDK..................',
    '..................zSSSzDgDDDD...................',
    '.................KcSSzDDDDD.....................',
    '.............KKKKrccJKccccYYYKK.KKK.............',
    '............KrrrKrccKYYyyYYYYJJKrrrK............',
    '............KrJJrJJJKLecccLYYJJKrJJK............',
    '............KrJJJJJKJLLccLLJoJJKrJJK............',
    '............KrJJJJJKJJLLLLJJOJJKrJJK............',
    '............KrJJJJKJJJJJKJJJJJJKrJJK............',
    '............KrJJJKJJJJJaKJJJJJJKrJJK............',
    '............KrJJJKJJJJJJKJJJJJJKrccK............',
    '.............KrJKrJJJJJJKJJJJJJKrccK............',
    '..............KKKrJJJJJaKJJJJJJKzSSz............',
    '.................KrJJJJJKJJJJJKzSSSSz...........',
    '.................KrJJJJJKJJJJJK.zSSz............',
    '.................KrJJJJQQJJJJJK..zz.............',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  clipboard: [
    '................................................',
    '..................KKKKKKKKKKKK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KTttTTTTTTTK..................',
    '..................KTTTTTTTTTTK..................',
    '..............KAaaaaaAAAAAAAAAAAAK..............',
    '...............KKKKKKKKKKKKKKKKKK...............',
    '...............HHhssssssssssssHHH...............',
    '...............HHHHSSSSSSSSSSHHHH...............',
    '................hHSBBBSSSSBBBSHH................',
    '................zHSsssSSSSsssSHz................',
    '...............zSHSSwESSsSwESSHSz...............',
    '...............zSHSSEESSsSEESSHSz...............',
    '................sDDCSSSSsSSSCDDs................',
    '................DdDDSMSzzSSSDDDD................',
    '................DdDDDSnmmnSDdDDD................',
    '................DDgDDDSSSSDDdDDD................',
    '................DDDdDDDgDDDDDDDD................',
    '.................KDdDDDgDdDgDdK.................',
    '..................KDDdDDDdDDDK..................',
    '...................DDdDDgDDDD...................',
    '.....................DDDDDD.....................',
    '.............KKK.KKYYYcGGcYYYKK.KKK.............',
    '............KrrrKJJYYYGGGGYYYJJKrrrK............',
    '............KrJJKrJUUUGGGGUUUJJKrJJK............',
    '............KrJJKrJUcccOccccUzKKrJJK............',
    '............KrJJKrJUccccccccUScrJJJK............',
    '............KrJJKrJUceeeeeecSzcJJJJK............',
    '............KrJJrKzUccccccccSzcJJJJK............',
    '............KrJJccSUceeeeeecUzKKKKK.............',
    '.............KrJcczSccccccccUJJK................',
    '..............KKrczSceeeeeecUJJK................',
    '................KKzUccccccccUJK.................',
    '.................KrUceeeecccUJK.................',
    '.................KrUccccccccUJK.................',
    '.................KrUUUUUUUUUUJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  thumbs: [
    '................................................',
    '..................KKKKKKKKKKKK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KTttTTTTTTTK..................',
    '..................KTTTTTTTTTTK..................',
    '..............KAaaaaaAAAAAAAAAAAAK..............',
    '...............KKKKKKKKKKKKKKKKKK...............',
    '...............HHhssssssssssssHHH...............',
    '...............HHHHSSSSSSSSSSHHHH...............',
    '................hHSBBBSSSSBBBSHH................',
    '................zHSsssSSSSsssSHz................',
    '...............zSHSSwESSsSEESSHSz...............',
    '...............zSHSSEESSsESSESHSz...............',
    '................sDDCSSSSsSSSCDDs................',
    '................DdDDSMSzzSSSDDDD................',
    '................DdDDDSnmmnSDdDDD................',
    '................DDgDDDSSSSDDdDDD................',
    '................DDDdDDDgDDDDDDDD...........V....',
    '.................KDdDDDgDdDgDdK............V....',
    '..................KDDdDDDdDDDK...........VVWVV..',
    '...................DDdDDgDDDD........zz....V....',
    '.....................DDDDDD.........zSSz...V....',
    '.............KKK.KKYYYccccYYYKK.KKK.zSSz........',
    '............KrrrKJJYYYYyyYYYYJJKrrrKzSSzzz......',
    '............KrJJKrJYYLecccLYYJJKrJJKzSSSSSz.....',
    '............KrJJKrJJJLLccLLJoJJKrJJrzsSsSSz.....',
    '............KrJJKrJJJJLLLLJJOJJKKrJJzSSSSSz.....',
    '............KrJJKrJJJJJJKJJJJJJKKrJJrzzzzz......',
    '............KrJJKrJJJJJaKJJJJJJK.KrJJccK........',
    '............KccJKrJJJJJJKJJJJJJK..KrJJK.........',
    '............KccJKrJJJJJJKJJJJJJK...KKK..........',
    '............zSSzKrJJJJJaKJJJJJJK................',
    '...........zSSSSzKrJJJJJKJJJJJK.................',
    '............zSSz.KrJJJJJKJJJJJK.................',
    '.............zz..KrJJJJQQJJJJJK.................',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  cheer: [
    '................................................',
    '..................KKKKKKKKKKKK..........O.......',
    '..................KAaaAAAAAAAK..................',
    '..............T...KAaaAAAAAAAK...VV.............',
    '..............T...KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '.....OO...........KAaAAAAAAAAK............T.....',
    '..................KTttTTTTTTTK.............T....',
    '..................KTTTTTTTTTTK..................',
    '..............KAaaaaaAAAAAAAAAAAAK..............',
    '...............KKKKKKKKKKKKKKKKKK...............',
    '...............HHhssssssssssssHHH...............',
    '...V...........HHHHSSSSSSSSSSHHHH............O..',
    '........zzz.....hHSBBBSSSSBBBSHH.....zzz.....O..',
    '.......zSSSz....zHSsssSSSSsssSHz....zSSSz.......',
    '.......zSSSz...zSHSSEESSsSEESSHSz...zSSSz.......',
    '.......zSSSz...zSHSESSESsESSESHSz...zSSSz.......',
    '.......KcccK....sDDCSSSSsSSSCDDs....KcccK.......',
    '.......KcccK....DdDDSMSzzSSSDDDD....KcccK.......',
    '.......KrJJrK...DdDDDSmmmmSDdDDD...KrJJJK.......',
    '....V...KrJJK...DDgDDDSqqSDDdDDD...KrJJK....O...',
    '...VVV..KrJJK...DDDdDDDgDDDDDDDD...KrJJK...OOO..',
    '....V...KrJJK....KDdDDDgDdDgDdK....KrJJK....O...',
    '.........KrJrK....KDDdDDDdDDDK....KrJJK.........',
    '.........KrJJrK....DDdDDgDDDD....KrJJJK.........',
    '..........KrJJK......DDDDDD......KrJJK..........',
    '..........KrJJrK.KKYYYccccYYYKK.KrJJJK..........',
    '...........KrJJrKJJYYYYyyYYYYJJKrJJJK...........',
    '............KrJJKrJYYLecccLYYJJKrJJK............',
    '............KrJJKrJJJLLccLLJoJJKrJJK............',
    '.............KKKKrJJJJLLLLJJOJJKKKK.............',
    '................KrJJJJJJKJJJJJJK................',
    '................KrJJJJJaKJJJJJJK................',
    '................KrJJJJJJKJJJJJJK................',
    '................KrJJJJJJKJJJJJJK................',
    '................KrJJJJJaKJJJJJJK................',
    '.................KrJJJJJKJJJJJK.................',
    '.................KrJJJJJKJJJJJK.................',
    '.................KrJJJJQQJJJJJK.................',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  pointup: [
    '................................................',
    '..................KKKKKKKKKKKK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaaAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KAaAAAAAAAAK..................',
    '..................KTttTTTTTTTK..................',
    '..................KTTTTTTTTTTK..................',
    '..............KAaaaaaAAAAAAAAAAAAK..............',
    '...............KKKKKKKKKKKKKKKKKK.O.....O.......',
    '...............HHhssssssssssssHHH..O...O........',
    '...............HHHHSSSSSSSSSSHHHH...............',
    '................hHSBBBSSSSBBBSHH.........OO.....',
    '................zHSsssSSSSsssSHz.....z..........',
    '...............zSHSSwESSsSwESSHSz...zSz.........',
    '...............zSHSSEESSsSEESSHSz...zSz.........',
    '................sDDCSSSSsSSSCDDs....zSz.........',
    '................DdDDSMSzzSSSDDDD....zSz.........',
    '................DdDDDSmmmmSDdDDD....zSzz........',
    '................DDgDDDSqqSDDdDDD....zSSSz.......',
    '................DDDdDDDgDDDDDDDD....zSSSz.......',
    '.................KDdDDDgDdDgDdK.....zsSsz.......',
    '..................KDDdDDDdDDDK......Kzzz........',
    '...................DDdDDgDDDD......KrccK........',
    '.....................DDDDDD........KrccK........',
    '.............KKK.KKYYYccccYYYKK.KKKKrJJK........',
    '............KrrrKJJYYYYyyYYYYJJKrrrKrJJK........',
    '............KrJJKrJYYLecccLYYJJKrJJrJJJK........',
    '............KrJJKrJJJLLccLLJoJJKrJJJJJJK........',
    '............KrJJKrJJJJLLLLJJOJJKKKrJJJJK........',
    '............KrJJKrJJJJJJKJJJJJJK..KrJJJK........',
    '............KrJJKrJJJJJaKJJJJJJK...KKrK.........',
    '............KccJKrJJJJJJKJJJJJJK.....K..........',
    '............KccJKrJJJJJJKJJJJJJK................',
    '............zSSzKrJJJJJaKJJJJJJK................',
    '...........zSSSSzKrJJJJJKJJJJJK.................',
    '............zSSz.KrJJJJJKJJJJJK.................',
    '.............zz..KrJJJJQQJJJJJK.................',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ],
  ponder: [
    '................................................',
    '..................KKKKKKKKKKKK..........kkkk....',
    '..................KAaaAAAAAAAK.........kWWWWk...',
    '..................KAaaAAAAAAAK........kWWWWWWk..',
    '..................KAaAAAAAAAAK........kWWWWWWk..',
    '..................KAaAAAAAAAAK.......kWWWWWWWWk.',
    '..................KAaAAAAAAAAK........kWkWkWkk..',
    '..................KTttTTTTTTTK........kWWWWWWk..',
    '..................KTTTTTTTTTTK.........kWWWWk...',
    '..............KAaaaaaAAAAAAAAAAAAK...kk.kkkk....',
    '...............KKKKKKKKKKKKKKKKKK...kWWk........',
    '...............HHhssssssssssssHHH...kWWk........',
    '...............HHHHSSSSSSSSSSHHHH....kk.........',
    '................hHSBBBSSSSBBBSHH...k............',
    '................zHSsssSSSSsssSHz..kWk...........',
    '...............zSHSSwESSsSwESSHSz..k............',
    '...............zSHSSEESSsSEESSHSz...............',
    '................sDDCSSSSsSSSCDDs................',
    '................DdDDSMSzzSSSDDDD................',
    '................DdDDDSnmmnSDdDDD................',
    '................DDgDDDSSSSDDdDDD................',
    '................DDDdDDDgDDDDDDDD................',
    '.................KDdDDDgDdDgDdK.................',
    '..................KDDdDDDdDDDK..................',
    '...................DDdDDgDDDD...................',
    '.....................DDDDDD.....................',
    '.............KKK.KKYYYccccYYYKK.KKK.............',
    '............KrrrKJJYYYYyyYYYYJJKrrrK............',
    '............KrJJKrJYYLecccLYYJJKrJJK............',
    '............KrJJKKKKKKKKKKKKKzzKrJJK............',
    '............KrJJrrrrrrrrrrrrrSSzrJJK............',
    '............KrJJJJJJJJJJJJJJJSSzrJJK............',
    '.............KrJzJJJJJJJJJJJJSSzrJJK............',
    '..............KzSzKKKKKKKKKKKzzrJJJK............',
    '..............zSSSzJJJJJJJJJJJJJJJJK............',
    '..............zSSSzJJJJJJJJJJJJJJJJK............',
    '...............zzzrJJJJJJJJJJJJJJJK.............',
    '.................KKKKKKKKKKKKKKKKK..............',
    '.................KrJJJJQQJJJJJK.................',
    '.................KrJJJKPPKJJJJK.................',
    '.................KKKKKKQQKKKKKK.................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................QpPPQ..QpPPQ..................',
    '..................FfFF....FfFF..................',
    '.................FfFFFF..FfFFFF.................',
    '..................QQQQQ...QQQQQ.................',
    '................xxxxxxxxxxxxxxxx................'
  ]
}



// Things Abe can hold up in his right hand. Each sits on his fist; the umbrella's shaft runs down into it.
const ITEMS: Record<HoldPose, { rows: string[]; center: number }> = {
  heart: { center: 40, rows: [
    '..KKK...KKK..',
    '.KXXXK.KXXXK.',
    'KXZZXXKXXXXXK',
    'KXZXXXXXXXXXK',
    'KXXXXXXXXXXXK',
    '.KXXXXXXXXXK.',
    '..KXXXXXXXK..',
    '...KXXXXXK...',
    '....KXXXK....',
    '.....KXK.....',
    '......K......'
  ] },
  coin: { center: 40, rows: [
    '...KKKKK...',
    '.KKNNNNNKK.',
    '.KNlNINNNK.',
    'KNlNIIIINNK',
    'KNlNINNNNIK',
    'KNNNIIIINIK',
    'KNNNNNNINIK',
    'KNNNIIIINIK',
    '.KNNNINNIK.',
    '.KKNNNNIKK.',
    '...KKKKK...'
  ] },
  calendar: { center: 40, rows: [
    '..K.....K..',
    'KKGKKKKKGKK',
    'KXXXXXXXXXK',
    'KXXXXXXXXXK',
    'KcccccccccK',
    'KcKcKcKcKcK',
    'KcccccccccK',
    'KcKcKcKcOcK',
    'KcccccccccK',
    'KcKcKceeecK',
    'KKKKKKKKKKK'
  ] },
  hourglass: { center: 40, rows: [
    'KKKKKKKKK',
    'KvvvvvvvK',
    '.KcccccK.',
    '.KcNNNcK.',
    '..KcNcK..',
    '...KNK...',
    '...KNK...',
    '..KcNcK..',
    '.KccNccK.',
    '.KcNNNcK.',
    '.KNNNNNK.',
    'KvvvvvvvK',
    'KKKKKKKKK'
  ] },
  umbrella: { center: 39, rows: [
    '......KKKKK......',
    '....KKRRuRRKK....',
    '..KKRRRRuRRRRKK..',
    '.KRRRRRuuuRRRRRK.',
    'KRRRRRRuuuRRRRRRK',
    'KKKKKKKKKKKKKKKKK',
    ...Array.from({ length: 18 }, () => '........K........')
  ] }
}

// The holding poses: the head from "point" on the body from "thumbs", with the thumb
// swapped for the item. Built once at load, same 48×48 grid as the drawn poses.
function hold({ rows: item, center }: { rows: string[]; center: number }) {
  const rows = [...DRAWN.point.slice(0, 26), ...DRAWN.thumbs.slice(26)]
  rows[26] = rows[26].slice(0, 36) + '.'.repeat(12)
  const x0 = center - Math.floor(item[0].length / 2)
  const y0 = 26 - item.length + 1
  item.forEach((line, dy) => {
    const row = rows[y0 + dy].split('')
    line.split('').forEach((c, dx) => { if (c !== '.') row[x0 + dx] = c })
    rows[y0 + dy] = row.join('')
  })
  return rows
}

const POSES: Record<PoseName, string[]> = {
  ...DRAWN,
  ...(Object.fromEntries(Object.entries(ITEMS).map(([name, item]) => [name, hold(item)])) as Record<HoldPose, string[]>),
}

const RECTS = Object.fromEntries(Object.entries(POSES).map(([name, rows]) => [name, toRects(rows)])) as Record<PoseName, ReturnType<typeof toRects>>

export function GuidePose({ name, size = 144, className }: { name: PoseName; size?: number; className?: string }) {
  return (
    <svg
      className={'guide-pose guide-pose--' + name + (className ? ' ' + className : '')} width={size} height={size} viewBox="0 0 48 48"
      shapeRendering="crispEdges" aria-hidden="true"
    >
      {RECTS[name].map((r, i) => <rect key={i} x={r.x} y={r.y} width={r.w} height={1} fill={r.fill} />)}
    </svg>
  )
}

// The thinking pose split into layers so the chat can animate it: Abe on his own,
// and his three thought clouds (small to big) as separate sprites.
const THINK_BODY = [
  '................................................',
  '..................KKKKKKKKKKKK..................',
  '..................KAaaAAAAAAAK..................',
  '..................KAaaAAAAAAAK..................',
  '..................KAaAAAAAAAAK..................',
  '..................KAaAAAAAAAAK..................',
  '..................KAaAAAAAAAAK..................',
  '..................KTttTTTTTTTK..................',
  '..................KTTTTTTTTTTK..................',
  '..............KAaaaaaAAAAAAAAAAAAK..............',
  '...............KKKKKKKKKKKKKKKKKK...............',
  '...............HHhssssssssssssHHH...............',
  '...............HHHHSSSSSSSSSSHHHH...............',
  '................hHSBBBSSSSBBBSHH................',
  '................zHSsssSSSSsssSHz................',
  '...............zSHSSwESSsSwESSHSz...............',
  '...............zSHSSEESSsSEESSHSz...............',
  '................sDDCSSSSsSSSCDDs................',
  '................DdDDSMSzzSSSDDDD................',
  '................DdDDDSnmmnSDdDDD................',
  '................DDgDDDSSSSDDdDDD................',
  '................DDDdDDDgDDDDDDDD................',
  '.................KDzzzDgDdDgDdK.................',
  '..................zSSSzDDdDDDK..................',
  '..................zSSSzDgDDDD...................',
  '.................KcSSzDDDDD.....................',
  '.............KKKKrccJKccccYYYKK.KKK.............',
  '............KrrrKrccKYYyyYYYYJJKrrrK............',
  '............KrJJrJJJKLecccLYYJJKrJJK............',
  '............KrJJJJJKJLLccLLJoJJKrJJK............',
  '............KrJJJJJKJJLLLLJJOJJKrJJK............',
  '............KrJJJJKJJJJJKJJJJJJKrJJK............',
  '............KrJJJKJJJJJaKJJJJJJKrJJK............',
  '............KrJJJKJJJJJJKJJJJJJKrccK............',
  '.............KrJKrJJJJJJKJJJJJJKrccK............',
  '..............KKKrJJJJJaKJJJJJJKzSSz............',
  '.................KrJJJJJKJJJJJKzSSSSz...........',
  '.................KrJJJJJKJJJJJK.zSSz............',
  '.................KrJJJJQQJJJJJK..zz.............',
  '.................KrJJJKPPKJJJJK.................',
  '.................KKKKKKQQKKKKKK.................',
  '..................QpPPQ..QpPPQ..................',
  '..................QpPPQ..QpPPQ..................',
  '..................QpPPQ..QpPPQ..................',
  '..................FfFF....FfFF..................',
  '.................FfFFFF..FfFFFF.................',
  '..................QQQQQ...QQQQQ.................',
  '................xxxxxxxxxxxxxxxx................'
]
const CLOUDS = [
  { x: 35, y: 13, rows: ['.k.', 'kWk', '.k.'] },
  { x: 37, y: 9, rows: ['.kk.', 'kWWk', 'kWWk', '.kk.'] },
  { x: 39, y: 2, rows: ['...kk...', '..kWWk..', '.kWWWWk.', 'kWWWWWWk', 'kWWWWWWk', '.kWWWWk.', '..kkkk..'] }
]
const THINK_RECTS = toRects(THINK_BODY)
const CLOUD_RECTS = CLOUDS.map((c) => ({ ...c, rects: toRects(c.rows) }))

export function ThinkingAbe({ size = 240, className }: { size?: number; className?: string }) {
  return (
    <svg
      className={'thinking-abe' + (className ? ' ' + className : '')} width={size} height={size} viewBox="0 0 48 48"
      shapeRendering="crispEdges" aria-hidden="true"
    >
      <g className="thinking-abe__body">
        {THINK_RECTS.map((r, i) => <rect key={i} x={r.x} y={r.y} width={r.w} height={1} fill={r.fill} />)}
      </g>
      {CLOUD_RECTS.map((c, n) => (
        <g key={n} className={'thinking-abe__cloud thinking-abe__cloud--' + (n + 1)} transform={`translate(${c.x} ${c.y})`}>
          <g>{c.rects.map((r, i) => <rect key={i} x={r.x} y={r.y} width={r.w} height={1} fill={r.fill} />)}</g>
        </g>
      ))}
    </svg>
  )
}
